- name: Install R Dependcy Packages
  apt: name={{item}} state=present
  with_items:
    - gdebi-core
    - libapparmor1

- name: Adding R Repository
  apt_repository: repo="deb http://cran.rstudio.com/bin/linux/ubuntu xenial/" state=present

- name: Adding R GPG Key
  apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9

- name: Installing R
  apt: name={{item}} state=present install_recommends=yes update_cache=yes
  with_items:
   - r-base
   - r-base-dev

- name: Install Commonly Used R Packages e.g. Bioconductor
  apt: name={{item}} state=present
  with_items:
    - r-cran-ggplot2
    - r-recommended
    - r-bioc-biobase
    - r-bioc-biocinstaller
    - r-bioc-edger
    - r-bioc-rsamtools
    - r-bioc-shortread

- name: Download Rstudio Server
  get_url:
    url=https://download2.rstudio.org/rstudio-server-1.1.456-amd64.deb
    dest={{source_dir}}/rstudio-server-1.1.456-amd64.deb

- name: Installing Rstudio Server
  shell: gdebi -n {{source_dir}}/rstudio-server-1.1.456-amd64.deb
  become: yes
  become_method: sudo

- name: Download Rstudio Desktop
  get_url:
    url=https://download1.rstudio.org/rstudio-xenial-1.1.456-amd64.deb
    dest={{source_dir}}/rstudio-1.1.456-amd64.deb

- name: Installing Rstudio Desktop
  shell: gdebi -n {{source_dir}}/rstudio-1.1.456-amd64.deb
  become: yes
  become_method: sudo
