- hosts: all
  become: yes
  vars:
    - workshop_user: genomics
    - source_dir: "/home/{{workshop_user}}/software/.source"
    - software_dir: "/home/{{workshop_user}}/software"
    - workshop_dir: "/home/{{workshop_user}}/workshop_materials"
    # sha-512 hash
    - genomics_user_password: $6$aeo311XfO$EaMB/xwcu/vD0t7/4kgfQU3pR45yvM2TXiI5o38Sv2cCP1soOwBA1c6kOZ1qTia4nwuRwDYNg35dbnxzCnXIs.
    # mysql native hash - SELECT PASSWORD("password") - also need to set in stacks_web.yaml
    #- stacks_user_password: '*39094635b39efded76637451cdbd294d41865007'
    # jupyter password https://jupyter-notebook.readthedocs.io/en/latest/public_server.html#preparing-a-hashed-password
    #- jupyter_password: 'sha1:0909a8ee63e4:7c0d5e80d50acbdc07d9e7f3ac66d028713e2825'
    
  pre_tasks:
    # Set up the workshop user with a SHA-512 crypted password using mkpasswd
    - name: Create {{workshop_user}} Workshop User
      user: name="{{workshop_user}}" group=workshop comment="{{workshop_user}} Workshop User" state=present shell=/bin/bash password={{genomics_user_password}}
      
    # Create genomics user Software Directories
    - name: Create Software Dir
      file: path={{software_dir}} state=directory owner="{{workshop_user}}" group=workshop
    - name: Create Software Source Dir
      file: path={{source_dir}} state=directory owner="{{workshop_user}}" group=workshop
    - name: Create Workshop Directory
      file: path={{workshop_dir}} state=directory owner="{{workshop_user}}" group=workshop
      
    - name: Installing Some Other Build Dependencies
      apt: name={{item}} state=present install_recommends=yes
      with_items:
       - libgsl0-dev
       - libsparsehash-dev
       - libhdf5-cpp-11 #blasr
       - libhdf5-dev #blasr
       - libfreetype6-dev #matplotlib
       - python3-pip

    # a bunch of aliasses I like to include
    - include: software_tasks/profile.yaml
      tags: alias, profile
    
    - name: Changing hostname to "{{workshop_user}}"
      lineinfile: dest=/etc/hostname regexp="^ip.*" line="{{workshop_user}}"
      tags: hostname

    - name: Changing hosts to "{{workshop_user}}"
      lineinfile: dest=/etc/hosts regexp="^127.*" line="127.0.0.1 localhost {{workshop_user}}"
      tags: hostname

    - include: software_tasks/hostname.yaml
      tags: hostname

    - include: software_tasks/motd.yaml
      tags: motd

    - include: software_tasks/desktop.yaml
      tags: desktop

  tasks:
    ### Commonly Required Programs/Libraries ###
    # bamtools is only in Ubuntu repos from 16.04+
    - name: Installing bamtools
      apt: name={{item}} state=present
      with_items:
       - bamtools
       - libbamtools-dev
       - libbamtools2.4.0
       - sra-toolkit
      tags: general, alignment, assembly, genomics, seqdqc, transcriptomics

    - name: Installing BioPerl - slow
      cpanm: name=CJFIELDS/BioPerl-1.6.924.tar.gz
      tags: general, alignment, assembly, genomics, seqdqc, bioperl

    - name: Installing BioPython
      pip: name=biopython state=present
      tags: general, alignment, assembly, genomics, seqdqc, biopython
    
    # Conda for Python 2.7
    #- include: software_tasks/conda.yaml version=2 prefix=/home/genomics/miniconda
    #  tags: general, conda, qiime, qiime2

    # Conda for Python 3.0
    - include: software_tasks/conda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, conda, qiime, qiime2

    # Add Bioconda repos for Conda with Python 3
    - include: software_tasks/bioconda.yaml version=3 prefix=/home/genomics/miniconda
      tags: general, conda, bioconda, qiime, qiime2

    ### Unix ###
    # Base is OK


    ### Sequencing Data Quality Control ###
    - include: software_tasks/seqtk.yaml
      tags: genomics, seqdqc, seqtk
      
    - include: software_tasks/trim_galore.yaml version=0.5.0
      tags: seqdqc, trim_galore
    
    - name: Installing cutadapt
      pip: name=cutadapt state=present
      tags: seqdqc, cutadapt

    - name: Install ea-utils 1.04.676, trimmomatic
      apt: name={{item}} state=present
      with_items:
       - ea-utils
       - trimmomatic
      tags: genomics, seqdqc
      
    # The Ubuntu fastqc package is broken!
    - include: software_tasks/fastqc.yaml version=0.11.7
      tags: fastqc

    - name: Installing multiqc
      pip: name=multiqc state=present
      tags: seqdqc, multiqc


    ### Alignment Methods ###
    # This requires > 4GB memory to install, so we ignore the errors
    # to allow the rest of the play to run through
    #- include: software_tasks/blasr.yaml
    #  tags: alignment, genomics, blasr
    #  ignore_errors: yes


    ### Genomics ###
    ## Previously Installed
    # FastQC, fastq-mcf, seqtk, blasr

    #- include: software_tasks/pilon.yaml version=1.21
    #  tags: genomics, pilon

    #- name: Installing vcftools
    #  apt: name=vcftools state=present
    #  tags: genomics, vcftools

    #- name: Installing mummer
    #  apt: name=mummer state=present
    #  tags: genomics, mummer, circlator, amos

    #- include: software_tasks/amos.yaml version=3.1.0
    #  tags: genomics, amos, circlator, minimus2

    #- name: Installing Circlator
    #  pip: name=circlator executable=pip3
    #  tags: genomics, circlator

    #- include: software_tasks/krona.yaml version=2.7
    #  tags: genomics, krona

    #- include: software_tasks/minimap.yaml
    #  tags: genomics, minimap, miniasm, assembly
     
    #- include: software_tasks/miniasm.yaml
    #  tags: genomics, minimap, minias, assembly

    #- include: software_tasks/nanopolish.yaml
    #  tags: genomics, nanopolish, assembly

    #- include: software_tasks/poretools.yaml
    #  tags: genomics, poretools, assembly

    # installs bowtie 1 and 2
    - include: software_tasks/bowtie.yaml version=2.2.9
      tags: genomics, bowtie, transcriptomics

    - include: software_tasks/bwa.yaml
      tags: genomics, bwa, gatb, circlator
      
    - include: software_tasks/samtools.yaml version=1.9
      tags: genomics, samtools, transcriptomics

    #- include: software_tasks/bcftools.yaml version=1.3.1
    #  tags: genomics, bcftools
      
    - name: Installing blast legacy & blast+
      apt: name={{item}} state=present
      with_items:
       - ncbi-blast+
       - ncbi-blast+-legacy
       - ncbi-tools-bin
       - ncbi-tools-x11
      tags: genomics, blast
      
    #- name: Installing EMBOSS tools (getorf)
    #  apt: name={{item}} state=present
    #  with_items:
    #   - emboss
    #   - emboss-data
    #   - emboss-doc
    #   - emboss-lib
    #   - jemboss
    #  tags: genomics, emboss
      
    #- name: Installing FastTree2
    #  apt: name=fasttree state=present
    #  tags: fasttree
    #- name: Install FastTree2 Links
    #  file: src=/usr/bin/fasttree dest=/usr/bin/FastTree state=link
    #  tags: fasttree
    #- name: Install FastTree2 MP Links
    #  file: src=/usr/bin/fasttreeMP dest=/usr/bin/FastTreeMP state=link
    #  tags: genomics, fasttree
      
    - include: software_tasks/igv.yaml version=2.4.10 sub=2.4
      tags: genomics, igv, transcriptomics
#IGV tools not in the broad link any more. Will only fix if needed
#    - include: software_tasks/igvtools.yaml version=2.4.10 sub=2.4
#      tags: genomics, igvtools, transcriptomics
      
    - name: Install bedtools
      apt: name=bedtools state=present
      tags: genomics, bedtools

    - include: software_tasks/qualimap.yaml version=2.2
      tags: genomics, qualimap

    - include: software_tasks/SPAdes.yaml version=3.11.1
      tags: assembly, genomics, spades, circlator

    - include: software_tasks/quast.yaml version=4.2
      tags: assembly, genomics, quast

   # - include: software_tasks/hmmer.yaml version=3.1b2
   #   tags: genomics, hmmer

   # - name: Installing Velvet Assembler
   #   apt: name={{item}} state=present
   #   with_items:
   #    - velvet
   #    - velvet-example
   #   tags: assembly, genomics, velvet

  #  - include: software_tasks/bam2fastq.yaml version=1.1.0
  #    tags: genomics, bam2fastq

   # - include: software_tasks/newick_utils.yaml
   #   tags: genomics, newick_utils

   # - include: software_tasks/picard_tools.yaml
   #   tags: genomics, picard_tools

   # - include: software_tasks/genomics_tutorial_extras.yaml
   #   tags: genomics, genomics_extras

   # - include: software_tasks/gatb-pipeline.yaml version=1.171
   #   tags: genomics, gatb
      
   # - include: software_tasks/minia.yaml version=2.0.7
   #   tags: genomics, assembly, minia, gatb

    ### Genome Assembly ###
    ## Previously Installed
    # velvet, SPAdes, QUAST, fastqc, minia, gatb

   # - include: software_tasks/kmergenie.yaml version=1.7016
   #   tags: assembly, kmergenie
   
   # - include: software_tasks/prokka.yaml
   #   tags: assembly, prokka, circlator

   # - include: software_tasks/canu.yaml
   #   tags: assembly, canu


    ### Introduction to R ###
    ## Previously Installed
    # r and r studio server/desktop

    - name: Installing littler
      apt: name=r-cran-littler state=present
      tags: r, phyloseq, littler

    - name: Installing ggplot2
      shell: "{{playbook_dir}}/scripts/install.r ggplot2"
      tags: r, ggplot2


    ### QIIME ###
    - name: Installing QIIME Dependencies
      pip: name={{item}} state=present
      with_items:
       - numpy
       - h5py
       - matplotlib
      tags: qiime, metagenomics
      
    - name: Install MAFFT QIIME Dependency
      apt: name=mafft state=present
      tags: qiime, qiime2

    # basic pip install of qiime
    - include: software_tasks/qiime_basic.yaml version=1.9.1
      tags: qiime, metagenomics

    # conda environment install qiime1
    #- include: software_tasks/qiime_env.yaml
    #  tags: qiime, metagenomics 

    # conda environment install qiime2 - DOING MANUALLY FOR NOW
    #- include: software_tasks/qiime2_env.yaml
    #  tags: qiime2, metagenomics

    #- include: software_tasks/jupyter.yaml
    #  tags: qiime, qiime2, jupyter, metagenomics
    

    ### PhyloSeq ###
    ## Previously Installed
    # r, r-studio-server/desktop, littler, ggplot2
    
    - include: software_tasks/phyloseq.yaml
      tags: phyloseq

    
    ### RAD-Seq / Stacks ###
    ## Previously Installed
    # MySQL (MariaDB) in Base Install

    #- name: Installing Stacks Dependencies
    #  apt: name={{item}} state=present
    #  with_items:
    #   - libdbd-mysql-perl
    #   - libsparsehash-dev
    #   - php7.0
    #   - php7.0-mysql
    #   - python-mysqldb
    #   - libspreadsheet-writeexcel-perl
    #  tags: radseq, stacks
 
    #- include: software_tasks/stacks.yaml version=1.44
    #  tags: radseq, stacks

    #- include: software_tasks/stacks_web.yaml
    #  tags: radseq, stacks, stacksweb

    #- include: software_tasks/raxml.yaml
    #  tags: radseq, raxml, trees

    #- name: Install gnuplot
    #  apt: name=gnuplot state=present
    #  tags: radseq, gnuplot

    # The default is to disable sse2 and sse4.1 extensions
    # as we have been burned before by some Amazon instances
    # not having those extensions available! 
    #- include: software_tasks/gmap_gsnap.yaml version=2016-08-24
    #  tags: radseq, gmap, gsnap, transcriptomics
   
    #- include: software_tasks/structure_console.yaml version=2.3.4
    #  tags: radseq, structure

    #- include: software_tasks/structure_frontend.yaml version=2.3.4
    #  tags: radseq, structure


    ### Transcriptomics ###
    ## Previously Installed
    # bowtie1, bioconductor, IGV, igvtools, samtools, gmap

    - include: software_tasks/r_transcriptomics.yaml
      tags: r, transcriptomics

    - include: software_tasks/rsem.yaml version=1.2.31
      tags: transcriptomics, rsem
    
    - name: Installing xpdf and lighttpd
      apt: name="{{item}}" state=present
      with_items:
        - xpdf
        - lighttpd
      tags: transcriptomics

    - include: software_tasks/trinity.yaml
      tags: trinity, transcriptomics

    - include: software_tasks/trinotate.yaml
      tags: transcriptomics, trinotate, transdecoder

    #- include: software_tasks/cbs_programs.yaml
    #  tags: trinity, cbs, signalp, tmhmm, rnammer, transcriptomics

  ## Finishing Touches
  post_tasks:  
    - name: Changing software/source user:group to genomics:workshop
      file: path=/home/genomics/software owner=genomics group=workshop recurse=yes
      tags: finish

    - shell: echo 'Now please run the Genomics Workshop Data Tasks Playbook'
      tags: finish
